<!DOCTYPE html>
<html>
<head>
    <title>Attendance Report - {{ $unit->code }}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <style>
        /* Basic Styles */
        body {
            font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
            font-size: 10pt;
            line-height: 1.5;
            color: #333;
            -webkit-print-color-adjust: exact; /* For better print output */
        }

        /* Header */
        .header {
            text-align: center;
            margin-bottom: 30px;
            padding-bottom: 15px;
            border-bottom: 2px solid #eee;
        }
        .header h1 {
            margin: 0;
            font-size: 24pt;
            color: #2c3e50;
            line-height: 1.2;
        }
        .header p {
            margin: 5px 0 0;
            font-size: 11pt;
            color: #555;
        }
        .header p strong {
            color: #1a1a1a;
        }

        /* Table Styles */
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 25px;
            table-layout: fixed; /* Helps with column width distribution */
        }
        th, td {
            border: 1px solid #ddd;
            padding: 10px 8px;
            text-align: left;
            word-wrap: break-word; /* Prevents long text from overflowing */
        }
        th {
            background-color: #f8f8f8;
            font-weight: bold;
            font-size: 9pt;
            color: #444;
            text-transform: uppercase;
        }
        td {
            font-size: 8.5pt;
        }

        /* Status Colors */
        .present {
            color: #28a745; /* Green */
            font-weight: bold;
        }
        .absent {
            color: #dc3545; /* Red */
            font-weight: bold;
        }
        .na {
            color: #6c757d; /* Grey */
            font-style: italic;
        }

        /* Alternating row colors */
        tbody tr:nth-child(even) {
            background-color: #f9f9f9;
        }

        /* Footer */
        .footer {
            text-align: center;
            margin-top: 40px;
            padding-top: 15px;
            border-top: 1px solid #eee;
            font-size: 8pt;
            color: #777;
        }
        .footer a {
            color: #007bff;
            text-decoration: none;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Attendance Report</h1>
        <p><strong>Unit:</strong> {{ $unit->name }} ({{ $unit->code }})</p>
        <p><strong>Course:</strong> {{ $unit->course->name }}</p>
        <p><strong>Level:</strong> {{ $unit->level->name ?? 'N/A' }}</p>
        <p><strong>Report Period:</strong> {{ $startDate->format('d M, Y') }} - {{ $endDate->format('d M, Y') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 5%;">#</th>
                <th style="width: 25%;">Student Name</th>
                <th style="width: 15%;">Reg. Number</th>
                @foreach($reportDates as $date)
                    <th style="width: {{ 55 / count($reportDates) }}%;">{{ \Carbon\Carbon::parse($date)->format('D, M d') }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @forelse($reportData as $index => $studentRecord)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $studentRecord['name'] }}</td>
                    <td>{{ $studentRecord['registration_number'] }}</td>
                    @foreach($reportDates as $date)
                        @php
                            $status = $studentRecord['presence'][$date] ?? 'N/A';
                            $class = '';
                            if ($status === 'Present') {
                                $class = 'present';
                            } elseif ($status === 'Absent') {
                                $class = 'absent';
                            } else {
                                $class = 'na';
                            }
                        @endphp
                        <td class="{{ $class }}">{{ $status }}</td>
                    @endforeach
                </tr>
            @empty
                <tr>
                    <td colspan="{{ 3 + count($reportDates) }}" style="text-align: center; padding: 20px;">
                        No student data found for this unit and period.
                    </td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Generated by the Attendance Management System on {{ \Carbon\Carbon::now()->format('d M, Y H:i:s') }} EAT.
        <br>
        &copy; {{ \Carbon\Carbon::now()->format('Y') }} Your University/Institution Name. All rights reserved.
    </div>
</body>
</html>